/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData bell_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_10 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_dark_mode_6724412 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_theme_6235211 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kebab_vertical = IconData(0xf349, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xf3bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xf55d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
